version: "3"
services:

# Cassandra
  cassandra:
    container_name: cassandra_service
    image: cassandra:latest
    networks:
      - nineleapsnet
    environment:
        WAIT_TIMEOUT: "60"
        JVM_OPTS: "-Dcassandra.consistent.rangemovement=false"
        CASSANDRA_CLUSTER_NAME: "NineleapsCluster"
        CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
        CASSANDRA_DC: "DATA"
    volumes:
      - /var/lib/cassandra
    ports:    
      - "9042:9042"
    restart: always


  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      networks:
        - nineleapsnet   

  kafka:
      image: wurstmeister/kafka
      depends_on:
        - zookeeper      
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.28.1.11:9092
        KAFKA_CREATE_TOPICS: "ORDER_SERVICE_TOPIC:1:1:compact"
      expose:
        - "9093"
        - "9092"
      ports:
        - "9092:9092"
      networks:
        nineleapsnet:
          ipv4_address: 172.28.1.11
    
# Registry And Discovery
  registry:
    container_name: registry_discovery_service
    image: registry
    build:
      context: nineleaps-registry
      dockerfile: /home/vivek/workspace/nineleaps/nineleaps-poc/nineleaps-registry/Dockerfile
    volumes:
      - /data/registry_discovery_service
    ports:
      - "8761:8761"
    networks:
      - nineleapsnet
      
#API-Gateway      
  gateway:
    container_name: gateway_service
    image: gateway
    build:
      context: nineleaps-gateway
      dockerfile: /home/vivek/workspace/nineleaps/nineleaps-poc/nineleaps-gateway/Dockerfile
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://registry:8761/eureka/ -DCASSANDRA_URI=cassandra -DCASSANDRA_PORT=9042
    links:
      - registry
    ports:
      - "8765:8765"
    restart: on-failure
    networks:
      - nineleapsnet

#Supplier Service      
  supplier:
    container_name: supplier_service
    image: supplier:latest
    build:
      context: supplier
      dockerfile: /home/vivek/workspace/nineleaps/nineleaps-poc/supplier/Dockerfile
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://registry:8761/eureka -DKAFKA_SERVER=172.28.1.11:9092 -DCASSANDRA_URI=cassandra -DCASSANDRA_PORT=9042
    links:
      - cassandra
      - registry
      - gateway
    networks:
      nineleapsnet:
        ipv4_address: 172.28.1.12
    ports: 
      - "8010:8010"    
    restart: always

#Product-Service      
  product:
    container_name: product_service
    image: product:latest
    build:
      context: product
      dockerfile: /home/vivek/workspace/nineleaps/nineleaps-poc/product/Dockerfile
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://registry:8761/eureka -DKAFKA_SERVER=172.28.1.11:9092 -DCASSANDRA_URI=cassandra -DCASSANDRA_PORT=9042
    links:
      - cassandra
      - registry
      - gateway
    networks:
      nineleapsnet:
        ipv4_address: 172.28.1.13
    ports: 
      - "8020:8020"
    restart: always
      
  order:
    container_name: order_service
    image: order:latest
    build:
      context: order
      dockerfile: /home/vivek/workspace/nineleaps/nineleaps-poc/order/Dockerfile
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://registr:8761/eureka -DKAFKA_SERVER=172.28.1.11:9092 -DCASSANDRA_URI=cassandra -DCASSANDRA_PORT=9042
    links:
      - cassandra
      - registry
      - gateway
    networks:
      nineleapsnet:
        ipv4_address: 172.28.1.14
    ports: 
      - "8030:8030"
    restart: always

networks:
  nineleapsnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.28.1.0/16
      

